# Generated by Django 5.0.14 on 2025-09-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_researcher', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, default='', max_length=64)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('api_jwt', models.TextField(blank=True, default='')),
                ('api_jwt_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
